import { AchievementBadge, UserProfile } from '../../types/curriculum';
import { TestResult } from '../../types';

export const ALL_ACHIEVEMENTS: AchievementBadge[] = [
  {
    id: 'first-step',
    title: 'İlk Adım',
    titleEn: 'First Step',
    description: 'İlk klavye hız testinizi başarıyla tamamlayın.',
    descriptionEn: 'Complete your first typing speed test.',
    icon: 'Flag',
    category: 'special',
  },
  {
    id: 'wpm-40',
    title: 'Hızlı Parmaklar',
    titleEn: 'Swift Fingers',
    description: 'Bir testte 40 WPM hız sınırını aşın.',
    descriptionEn: 'Exceed 40 WPM in any typing test.',
    icon: 'Zap',
    category: 'speed',
  },
  {
    id: 'wpm-60',
    title: 'Profesyonel Yazıcı',
    titleEn: 'Professional Typist',
    description: '60 WPM hız barajına ulaşarak ofis standardını geçin.',
    descriptionEn: 'Reach 60 WPM passing office benchmarks.',
    icon: 'Award',
    category: 'speed',
  },
  {
    id: 'wpm-80',
    title: '80 WPM Kulübü',
    titleEn: '80 WPM Club',
    description: '80 WPM hızına ulaşarak en iyi %10 typist arasına girin.',
    descriptionEn: 'Reach 80 WPM placing in the top 10% of typists.',
    icon: 'Trophy',
    category: 'speed',
  },
  {
    id: 'wpm-100',
    title: 'Işık Hızı (100+ WPM)',
    titleEn: 'Light Speed (100+ WPM)',
    description: '100 WPM üzerinde inanılmaz bir hıza ulaşın.',
    descriptionEn: 'Reach an incredible 100+ WPM velocity.',
    icon: 'Flame',
    category: 'speed',
  },
  {
    id: 'accuracy-98',
    title: 'Keskin Nişancı',
    titleEn: 'Sharpshooter',
    description: 'Bir testte %98 ve üzeri doğruluk elde edin.',
    descriptionEn: 'Achieve 98%+ accuracy in a completed test.',
    icon: 'Target',
    category: 'accuracy',
  },
  {
    id: 'accuracy-100',
    title: 'Kusursuz Vuruş (%100)',
    titleEn: 'Flawless Touch (100%)',
    description: 'Sıfır hata ile %100 kusursuz bir test tamamlayın.',
    descriptionEn: 'Complete a test with zero errors (100% accuracy).',
    icon: 'Sparkles',
    category: 'accuracy',
  },
  {
    id: 'consistency-90',
    title: 'Metronom Ritmi',
    titleEn: 'Metronome Rhythm',
    description: '%90 üzerinde parmak ritim tutarlılığı sağlayın.',
    descriptionEn: 'Achieve 90%+ keystroke timing consistency.',
    icon: 'Activity',
    category: 'accuracy',
  },
  {
    id: 'streak-3',
    title: '3 Günlük Seri',
    titleEn: '3-Day Streak',
    description: '3 gün üst üste en az 1 test tamamlayarak pratik serisi başlatın.',
    descriptionEn: 'Practice 3 consecutive days.',
    icon: 'Calendar',
    category: 'streak',
  },
  {
    id: 'streak-7',
    title: 'Haftalık Şampiyon',
    titleEn: 'Weekly Champion',
    description: '7 gün kesintisiz her gün antrenman yapın.',
    descriptionEn: 'Maintain a 7-day uninterrupted practice streak.',
    icon: 'Flame',
    category: 'streak',
  },
  {
    id: 'streak-30',
    title: 'Demir İrade (30 Gün)',
    titleEn: 'Iron Will (30 Days)',
    description: 'Tam 30 gün boyunca her gün klavye hızınızı geliştirin.',
    descriptionEn: 'Practice everyday for 30 consecutive days.',
    icon: 'Crown',
    category: 'streak',
  },
  {
    id: 'lesson-module-1',
    title: 'Ev Sırası Ustası',
    titleEn: 'Home Row Master',
    description: 'Dersler bölümünde Modül 1\'in tüm derslerini başarıyla bitirin.',
    descriptionEn: 'Complete all lessons in Module 1.',
    icon: 'BookOpen',
    category: 'lessons',
  },
  {
    id: 'lesson-master',
    title: 'Ders Yıldızı',
    titleEn: 'Lesson Star',
    description: '5 farklı dersten 3 yıldız tam puan alın.',
    descriptionEn: 'Earn 3 stars across 5 different lessons.',
    icon: 'Star',
    category: 'lessons',
  },
  {
    id: 'f-klavye-kesfi',
    title: 'Milli Standart (F Klavye)',
    titleEn: 'National Standard (F Layout)',
    description: 'Türkçe F klavye düzeninde en az bir test tamamlayın.',
    descriptionEn: 'Complete at least one test using Turkish F layout.',
    icon: 'Compass',
    category: 'special',
  },
  {
    id: 'marathon-5min',
    title: 'Dayanıklılık Maratonu',
    titleEn: 'Endurance Marathon',
    description: '5 dakikalık (300s) zorlu dayanıklılık testini tamamlayın.',
    descriptionEn: 'Complete a full 5-minute endurance speed test.',
    icon: 'Clock',
    category: 'special',
  },
  {
    id: 'night-owl',
    title: 'Gece Kuşu',
    titleEn: 'Night Owl',
    description: 'Gece 00:00 ile 04:00 saatleri arasında test tamamlayın.',
    descriptionEn: 'Complete a test between midnight and 4 AM.',
    icon: 'Moon',
    category: 'special',
  },
  {
    id: 'daily-challenge-hero',
    title: 'Meydan Okuyucu',
    titleEn: 'Challenger',
    description: 'Günün resmi meydan okuma testine katılın.',
    descriptionEn: 'Participate in the Daily Challenge test.',
    icon: 'Shield',
    category: 'special',
  },
  {
    id: 'word-sprinter',
    title: '100 Kelime Fırtınası',
    titleEn: '100 Words Sprinter',
    description: '100 kelimelik test modunu başarıyla tamamlayın.',
    descriptionEn: 'Complete the 100-word speed sprint.',
    icon: 'Wind',
    category: 'speed',
  },
  {
    id: 'zen-master',
    title: 'Zen Odaklanma',
    titleEn: 'Zen Focus',
    description: 'Zen modu açıkken dikkatiniz dağılmadan bir test bitirin.',
    descriptionEn: 'Finish a test with Zen focus mode active.',
    icon: 'Eye',
    category: 'special',
  },
  {
    id: 'typingfastest-elite',
    title: 'Elit Typist',
    titleEn: 'Elite Typist',
    description: 'Toplam 50 hız testini başarıyla tamamlayın.',
    descriptionEn: 'Complete a cumulative total of 50 tests.',
    icon: 'Gem',
    category: 'special',
  },
];
