import { CurriculumModule } from '../../types/curriculum';

export const TURKISH_Q_MODULES: CurriculumModule[] = [
  {
    id: 1,
    title: 'Modül 1: Ev Sırası (Home Row)',
    titleEn: 'Module 1: Home Row Basics',
    description: 'Doğru el pozisyonu, F ve J kılavuz tuşları ve temel sıra harfleri.',
    descriptionEn: 'Proper hand posture, F & J tactile anchors, and base home row keys.',
    level: 'beginner',
    lessons: [
      {
        id: 'tr-q-m1-l1',
        layout: 'tr-q',
        module: 1,
        lessonNumber: 1,
        title: 'F ve J Kılavuz Tuşları',
        titleEn: 'F and J Anchor Keys',
        description: 'İşaret parmaklarınızı F ve J tuşlarındaki çıkıntılara yerleştirin.',
        descriptionEn: 'Place index fingers on F and J tactile indicator bumps.',
        objectives: ['F ve J tuşlarını hissetmek', 'Klavyeye bakmadan işaret parmaklarını yerleştirmek'],
        estimatedMinutes: 2,
        prerequisiteIds: [],
        steps: [
          {
            type: 'instruction',
            content: 'Sol işaret parmağınızı F tuşundaki, sağ işaret parmağınızı ise J tuşundaki kabartıya yerleştirin. Bu iki tuş ellerinizin ana çıpasıdır.',
            keyFocus: ['f', 'j'],
            fingerFocus: ['left-index', 'right-index'],
          },
          {
            type: 'exercise',
            content: 'F ve J tuşlarını eşit ritimde yazın.',
            exerciseText: 'f j f j ff jj fjf jfj fff jjj ffff jjjj',
            targetWpm: 15,
            targetAccuracy: 92,
          },
        ],
      },
      {
        id: 'tr-q-m1-l2',
        layout: 'tr-q',
        module: 1,
        lessonNumber: 2,
        title: 'Sol El Ev Sırası: A - S - D - F',
        titleEn: 'Left Hand Home Row: A - S - D - F',
        description: 'Sol elinizin serçe, yüzük, orta ve işaret parmaklarını ev sırasına alıştırın.',
        descriptionEn: 'Train left pinky, ring, middle, and index fingers on A-S-D-F.',
        objectives: ['A, S, D, F parmak koordinasyonu', 'Bilekleri kaldırma alışkanlığı'],
        estimatedMinutes: 3,
        prerequisiteIds: ['tr-q-m1-l1'],
        steps: [
          {
            type: 'instruction',
            content: 'Sol el: Serçe (A), Yüzük (S), Orta (D), İşaret (F). Parmaklarınızı tuşların üzerinde kavisli tutun.',
            keyFocus: ['a', 's', 'd', 'f'],
            fingerFocus: ['left-pinky', 'left-ring', 'left-middle', 'left-index'],
          },
          {
            type: 'exercise',
            content: 'Sol el harflerini sırayla ve karışık yazın.',
            exerciseText: 'asdf fdsa asdf fdsa asda sdfs dfaa fssa fada safa dadas',
            targetWpm: 18,
            targetAccuracy: 90,
          },
        ],
      },
      {
        id: 'tr-q-m1-l3',
        layout: 'tr-q',
        module: 1,
        lessonNumber: 3,
        title: 'Sağ El Ev Sırası: J - K - L - Ş',
        titleEn: 'Right Hand Home Row: J - K - L - Ş',
        description: 'Sağ elinizin işaret, orta, yüzük ve serçe parmaklarıyla J, K, L ve Ş tuşları.',
        descriptionEn: 'Train right hand on J, K, L, and Turkish specific Ş key.',
        objectives: ['J, K, L, Ş tuş koordinasyonu', 'Türkçe Ş harfi kullanımı'],
        estimatedMinutes: 3,
        prerequisiteIds: ['tr-q-m1-l2'],
        steps: [
          {
            type: 'instruction',
            content: 'Sağ el: İşaret (J), Orta (K), Yüzük (L), Serçe (Ş). Ş harfi Türkçe Q klavyede serçe parmağın altındadır.',
            keyFocus: ['j', 'k', 'l', 'ş'],
            fingerFocus: ['right-index', 'right-middle', 'right-ring', 'right-pinky'],
          },
          {
            type: 'exercise',
            content: 'Sağ el harflerini akıcı şekilde yazın.',
            exerciseText: 'jklş şlkj jklş jkl şlk jlk şkj lkş jşl kşj lşj şlkş',
            targetWpm: 18,
            targetAccuracy: 90,
          },
        ],
      },
      {
        id: 'tr-q-m1-l4',
        layout: 'tr-q',
        module: 1,
        lessonNumber: 4,
        title: 'Ev Sırası Birleşimi ve İlk Kelimeler',
        titleEn: 'Home Row Combined & First Words',
        description: 'İki elinizi birleştirerek ev sırasındaki harflerle anlamlı Türkçe kelimeler üretin.',
        descriptionEn: 'Combine both hands to type real Turkish words with home row letters.',
        objectives: ['İki el koordinasyonu', 'Boşluk (Space) tuşunu başparmakla kullanmak'],
        estimatedMinutes: 4,
        prerequisiteIds: ['tr-q-m1-l3'],
        steps: [
          {
            type: 'exercise',
            content: 'Ev sırasındaki harflerle Türkçe kelimeler yazın.',
            exerciseText: 'ada saf sal kasa fala şaka şal dal fala kasa afas adalasa safaş',
            targetWpm: 22,
            targetAccuracy: 92,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Modül 2: Üst Sıra ve Sesli Harfler',
    titleEn: 'Module 2: Top Row & Vowels',
    description: 'E, R, T, Y, U, I, O, P ve Türkçe özel harfler Ğ ve Ü tuşları.',
    descriptionEn: 'Master top row keys including Turkish vowels and Ğ, Ü.',
    level: 'elementary',
    lessons: [
      {
        id: 'tr-q-m2-l1',
        layout: 'tr-q',
        module: 2,
        lessonNumber: 1,
        title: 'E ve I Tuşları (Orta Parmaklar)',
        titleEn: 'E and I Keys (Middle Fingers)',
        description: 'D ve K parmaklarınızı yukarı uzatarak E ve I harflerine erişin.',
        descriptionEn: 'Stretch middle fingers upward from D and K to reach E and I.',
        objectives: ['Orta parmak uzanışları', 'Türkçe noktasız I kullanımı'],
        estimatedMinutes: 3,
        prerequisiteIds: ['tr-q-m1-l4'],
        steps: [
          {
            type: 'instruction',
            content: 'Sol orta parmağınızı D tuşundan E tuşuna; sağ orta parmağınızı K tuşundan I (noktasız ı) tuşuna uzatın.',
            keyFocus: ['e', 'ı'],
            fingerFocus: ['left-middle', 'right-middle'],
          },
          {
            type: 'exercise',
            content: 'E ve I harflerini ev sırası ile birleştirin.',
            exerciseText: 'dede kıkı eda ada elle ılık efe fide kale kedi sele kele',
            targetWpm: 22,
            targetAccuracy: 90,
          },
        ],
      },
      {
        id: 'tr-q-m2-l2',
        layout: 'tr-q',
        module: 2,
        lessonNumber: 2,
        title: 'Türkçe Özel Harfler: Ğ ve Ü',
        titleEn: 'Turkish Special Characters: Ğ and Ü',
        description: 'Sağ serçe parmağın üst sıradaki Türkçe karakter uzanışları.',
        descriptionEn: 'Right pinky upper stretches for unique Turkish Ğ and Ü keys.',
        objectives: ['Ğ ve Ü tuşlarını ezberlemek', 'Sağ serçe esnekliği'],
        estimatedMinutes: 3,
        prerequisiteIds: ['tr-q-m2-l1'],
        steps: [
          {
            type: 'instruction',
            content: 'P tuşunun hemen sağında Ğ ve Ü tuşları yer alır. İki tuşa da sağ el serçe parmağınız uzanır.',
            keyFocus: ['ğ', 'ü'],
            fingerFocus: ['right-pinky'],
          },
          {
            type: 'exercise',
            content: 'Ğ ve Ü harfleri içeren Türkçe kelimeler.',
            exerciseText: 'ağa dağ bağ düğüm gül süt sağ yağ üye güç düğme',
            targetWpm: 24,
            targetAccuracy: 92,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: 'Modül 3: Alt Sıra ve Türkçe Özel Harfler',
    titleEn: 'Module 3: Bottom Row & Special Characters',
    description: 'Z, X, C, V, B, N, M ve Türkçe Ö ile Ç harfleri.',
    descriptionEn: 'Bottom row navigation including Turkish Ö and Ç.',
    level: 'intermediate',
    lessons: [
      {
        id: 'tr-q-m3-l1',
        layout: 'tr-q',
        module: 3,
        lessonNumber: 1,
        title: 'Ö ve Ç Tuşları',
        titleEn: 'Ö and Ç Keys',
        description: 'M tuşunun sağındaki Ö (sağ orta) ve Ç (sağ yüzük) tuşları.',
        descriptionEn: 'Learn Ö (right middle) and Ç (right ring) on the bottom row.',
        objectives: ['Ö ve Ç harflerini doğru parmakla basmak'],
        estimatedMinutes: 3,
        prerequisiteIds: ['tr-q-m2-l2'],
        steps: [
          {
            type: 'exercise',
            content: 'Ö ve Ç içeren zengin Türkçe kelime egzersizi.',
            exerciseText: 'çöl çok çam göz göl özel açık çiçek çilek çekiç özlem',
            targetWpm: 25,
            targetAccuracy: 92,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Modül 4: Hız ve Cümle Akıcılığı',
    titleEn: 'Module 4: Speed Bursts & Sentences',
    description: 'Tüm klavyeyi birleştiren tam cümleler ve ritmik hız antrenmanı.',
    descriptionEn: 'Full sentences and rhythm conditioning across the whole keyboard.',
    level: 'advanced',
    lessons: [
      {
        id: 'tr-q-m4-l1',
        layout: 'tr-q',
        module: 4,
        lessonNumber: 1,
        title: 'Türkçe Akıcı Cümleler',
        titleEn: 'Fluent Turkish Sentences',
        description: 'Gerçek hayatta sık kullanılan akıcı cümle kalıpları.',
        descriptionEn: 'Real-world sentence flow and natural cadence.',
        objectives: ['35+ WPM akıcı yazma', '%95 üzeri doğruluk'],
        estimatedMinutes: 5,
        prerequisiteIds: ['tr-q-m3-l1'],
        steps: [
          {
            type: 'exercise',
            content: 'Tam cümlelerle hız ve akıcılık testi.',
            exerciseText: 'güneşli bir sabah yürüyüşe çıkmak insana huzur verir ve zihni dinlendirir. doğru parmaklarla çalışmak zamanla yazma hızını iki katına çıkarır.',
            targetWpm: 35,
            targetAccuracy: 94,
          },
        ],
      },
    ],
  },
];
